### ISSUE TITLE
Improved Simulation to work without token approval or tokens

### ISSUE THREAD

**Issue by mattiaslightstone** [Component-fi/YieldTokenCompounding#16]
Currently in order to simulate a transaction the user first needs to approve token, and have the simulated number of tokens in their active wallet.

This is undesireable due to mainnet gas costs.

Edit:
To elaborate on why this is. The simulation is done through a callStatic function call, in order to simulate the real price impact that these repeated transactions would have. This is where we come to the problem. In order to simulate, the contract needs to have the base tokens approved by the user.

If anyone knows of a way to simulate multiple transactions in one, then this can be solved.

**Comment by mattiaslightstone** [comment]
Suggested solution. New contract that leverages the YTC contract.

This contracts.
1. Accepts a call paid for in eth, that includes the call data it should forward to the YTC contract
2. Swaps eth to the base asset (swap or zap into curve lp tokens)
3. Approves base asset on the YTC Contract
4. Executes compound function on the YTC
5. Either swaps base tokens back for eth, or keeps them as is
6.  Returns YTC and basetokens/eth to the user

If steps 1 and 5 are generalized they can accept any token as payment, and end with any other token. This would be an implementation of "decollateralize" which kills two birds with one stone.

This contract is also useful for using to YTC with flashloans, as exotic tokens like crvLPs wont be available for loans.

**Comment by mattiaslightstone** [comment]
Update: Slight change of design. Simulations will leverage zapper's API and consumer contracts to handle base asset swaps. Because simulations 

Frontend
1. User inputs simulation values into frontend including the number of base tokens as input ( W )
2. The frontend calculates ~ how much ETH would be required to swap for W base tokens. ( X )
3. Zapper API is called at one of two endpoints (exchange quote, or curve zap in)
4. The zapper api returns calldata, and a contract address for the swap/zap-in
5. Impersonate an account with more than X of eth (VB?)
6. Make a static call to the YTCZap contract with all calldata required for a normal YTC compound + zapper calldata and contract address, as well as a value of X Eth.

Contract
1. YTCZap contract passes the calldata to the Zapper consumer executing a swap/zap from X Eth -> W base tokens.
2. YTCZap contract approves YTC contract for W base Tokens
3. YTCZap calls YTC.compound receiving back Y yield tokens, and Z base tokens
4. YTCZap transfers Y yield tokens, and Z base tokens back to the original calling address

There are some checks that need to be done to protect against slippage, and such, but this is the basic design.

**Comment by reemlovesdefi** [comment]
simulate from burn address 0x00

if ETH dies we will have issues, but yolo.

**Comment by mattiaslightstone** [comment]
^ Related to re'em's comment. I had to go with the alternative blackhole 0x0...dead as USDC blocks transfers to the 0x0...0 burn address.

**Comment by mattiaslightstone** [comment]
Contract and frontend is up on the private dev-net, testing, sc review and FE optimizations are still in the works.

**Comment by mattiaslightstone** [comment]
These contracts will be similar to those used for de-collateralize, zapping in, swapping after a flashloan etc..., however for expediency this contract will be used solely for simulation. This lets us get it on mainnet without the need for audits.

Restricting who can call the contract to the burn address, makes it impossible for anyone to accidentally call the function, and lose their funds. I'm not sure that this guardrail is necessary, i.e. don't send transactions to contracts when you don't know what they do!
